### ISSUE TITLE
support CustomResourceDefinitions v1 and v1beta1

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#106]
kubernetes-client 4.12.0 supports CustomResourceDefinitions in v1 and v1beta1. We currently only display v1beta1, we should be able to display both.

**Comment by adietish** [comment]
@jeffmaury thoughts?

**Comment by lstocchi** [comment]
I think that only the latest version should be shown by default, so v1 in this case. If there are two or more versions, the older ones are marked as deprecated no? Maybe we can add a setting that if it's true the tree also show the older versions?

**Comment by adietish** [comment]
we decided to go for v1 only because of the days that went by since v1 was introduced. Closing.
