### ISSUE TITLE
Use newer IDEA in gradle.properties

### ISSUE THREAD

**Issue by jkopriva** [redhat-developer/intellij-kubernetes#111]
This ide is 2 years old:   
ideaVersion=IC-2018.3

Maybe we could update to newer version.

**Comment by jeffmaury** [comment]
The rule of thumb is that we have the policy to be compatible with most IJ versions. There is a workflow that ensure the plugin compiles against all IJ versions starting from the oldest

**Comment by jkopriva** [comment]
ok, thanks!

**Comment by adietish** [comment]
@jkopriva We should require the oldest possible IDEA and keep thing compatible to all newer versions as @jeffmaury pointed out. The property in gradle.properties is the minimum required version. Our integration tests make sure that we're compatible to newer versions. I'd thus think that things are fine as they are. 
Closing.
