### ISSUE TITLE
Error codes could be clearer

### ISSUE THREAD

**Issue by olkornii** [redhat-developer/intellij-kubernetes#173]
I think it's worth showing the cause of the error (for example, "not enough rights") or something like that. (see screenshot)
![image](https://user-images.githubusercontent.com/60704619/108184554-9f87fb00-710b-11eb-9d3c-12080f3a68cc.png)

**Comment by adietish** [comment]
@olkornii fully agree on this one. This is duplicate though, I had filed this in #28. I'll copy your screenshot over to it.
Closing as duplicate.
