### ISSUE TITLE
Editor notification is not disappearing

### ISSUE THREAD

**Issue by olkornii** [redhat-developer/intellij-kubernetes#206]
depends on #178

Steps to reproduce:
We have 2 projects: A and B -> open project A in editor -> delete project A from console -> editor shows the notification, that project was deleted -> close editor -> open project B in editor and see that notification is still here

**Comment by adietish** [comment]
I tried to reproduce this issue using minikube but failed to do so. Is there maybe anything missing in the steps? Can you please try again to replicate it?

**Comment by adietish** [comment]
found a different error case that seems related:

**Steps:**
1. ASSERT: have an openshift cluster with 1+ project
2. EXEC: in resource tree: select a project & pick "Edit..." 
3. ASSERT: editor with project shows up

**Result:**
Editor is reporting that the project was deleted

**Expected result:**
Editor should **Not** show the notification that says that the project is deleted.

**Comment by adietish** [comment]
@olkornii pushed the fixed in PR #178

**Comment by olkornii** [comment]
@adietish cannot reproduce anymore. Works for me.
