### ISSUE TITLE
Resource editor: should show modification mark if text is edited but not saved

### ISSUE THREAD

**Issue by olkornii** [redhat-developer/intellij-kubernetes#210]
Need to show "star" when file was modified.
![modification_marker](https://user-images.githubusercontent.com/60704619/118476457-d1f6c380-b70d-11eb-8af2-d11379d75ca5.png)

**Comment by olkornii** [comment]
fixes #202

**Comment by adietish** [comment]
Current impl in #178 doesn't know a unsaved state of the editor any more. All changes are immediately saved as it is common in IJ (See https://github.com/redhat-developer/intellij-kubernetes/pull/178#issuecomment-845956330). This issue thus doesn't exist any more if current state of #178 makes it to master.

**Comment by adietish** [comment]
This wont be implemented. Current strategy is to never have dirty editors, let intellij save to the local whenever it deems necessary (no veto) and inform the user of differences to the cluster resource via notifications.
Closing.
