### ISSUE TITLE
[Question] Custom resource templates

### ISSUE THREAD

**Issue by gAmUssA** [redhat-developer/intellij-kubernetes#230]
Hello team

Thanks for the plugin. Extends native IntelliJ functionality nicely.
Question is subject - how to add custom resources so they appear as templates. 

Thank you

**Comment by jeffmaury** [comment]
Can you explain what do you mean by templates ?

**Comment by adietish** [comment]
@gAmUssA my guess is that you're referring to templates as they're available in vscode. Issue #98 requests this. Correct or missing your point? If that's the case we're not there yet, it'll get added at some point in the future. 
The best we can offer currently is that you have your template file on your disk, open it in intellij, edit an existing resource and paste your template manually into the editor. When finished editing, push the resource to the cluster. Works for you?

**Comment by adietish** [comment]
@gAmUssA Is  Issue #98 what you were after? Is the suggested workaround worthwhile for your use case?

**Comment by gAmUssA** [comment]
sorry for the delay, @adietish. I think I'm good for now!
Thank you
