### ISSUE TITLE
InvalidPathException: Illegal char <:> at index 16: \Repository Diff: application.yml

### ISSUE THREAD

**Issue by RafaelPuerta** [redhat-developer/intellij-kubernetes#258]
Hi team!

My stacktrace: https://gist.github.com/RafaelPuerta/2f1130568e6a6f3047468c5f6fcbbfa1

Operation system : windows 10 version 21H1
IDE :Intellij Ultiimate 2021.2.1 Build #IU-212508055

**Comment by adietish** [comment]
Hi Rafael

thanks for reporting!
Could you please share the application.yml that is causing this?
Is this occurring when you open (File > Open) this file in IDEA?

**Comment by adietish** [comment]
This happens when our code checks whether a given file is a file we can handle (to push or pull from cluster). Excerpt from the stacktrace:
```
at com.redhat.devtools.intellij.kubernetes.editor.ResourceFile$Factory.isResourceFile(ResourceFile.kt:80)
```
This jetbrains code seems to cause this:
```
VfsUtil.virtualToIoFile(file).toPath()
```

**Comment by adietish** [comment]
here's another scenario where our code is invoked with a different path, that's no local file:

1. ASSERT: have a uncommitted file
2. EXEC: git commit it via IDEA

**Result:** 
File comes up in `ResourceFile#isResourceFile` as 
```
LightVirtualFile: /Dummy.txt
```
The `virtualFile.filesystem.protocol` for this file is `mock`
My guess is that this file is used to store the commit message.
