### ISSUE TITLE
The yaml editor is very slow when using remote clusters

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#285]
One has to use a remote cluster (ex. aws instances started with our cluster bot) to experience this noticeably. When using minikube locally one hardly notices these freezes.

**Steps:**
1. ASSERT: use a remote cluster (ex. aws instances started with our cluster bot)
1. ASSERT: have an editor opened 
1. EXEC: modify the yaml

**Result:**
For your characters to appear once you hit the key takes a bit at times. While the IDE waits for the key strokes to appear nothing is clickable.

**Comment by aleskandro** [comment]
Hi, I see this still happening with:
- Kubernetes by red hat: 1.2.1.277
- IntelliJ IDEA 2023.3 (Ultimate Edition)
