### ISSUE TITLE
Add releases with the information and binary

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/intellij-kubernetes#293]
Currently the [Releases](https://github.com/redhat-developer/intellij-kubernetes/releases) Section is empty and we need to update the info and add build binary to it.

**Comment by adietish** [comment]
created the releases matching what we already provide in the JetBrains marketplace: https://github.com/redhat-developer/intellij-kubernetes/releases

**Comment by adietish** [comment]
@mohitsuman please verify.

**Comment by mohitsuman** [comment]
This looks great @adietish 👍🏼
