### ISSUE TITLE
As a user I want to control if my local file is overwritten from the cluster pull

### ISSUE THREAD

**Issue by brunnels** [redhat-developer/intellij-kubernetes#319]
There is a lot of loaded configuration from the server that is not in my local file and I don't want to see it unless there was an option to diff with the cluster.

I certainly want a way to prevent my local file from being clobbered when I open it and the changes are pulled from the cluster.

**Comment by adietish** [comment]
@brunnels thanks for filing. I fully agree on being annoying to have the clutter added to your yaml/json as it gets pulled from server. The current idea is to have it (automatically) removed. Ideally with a switch in the preferences, see #274 
Would that fit your needs?

**Comment by brunnels** [comment]
@adietish Yes, that would be ideal.  It should also try to respect formatting.  

For instance, I have a helm chart with `valuesContent` that looks like this:
```---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ombi
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: ombi
  targetNamespace: media
  valuesContent: |-
    image:
      repository: ghcr.io/linuxserver/ombi
      tag: version-v4.0.1430
    env:
      TZ: "America/Chicago"
      PGID: 568
      PUID: 568
    initContainers:
      chmod-config:      
        name: chmod-config
        image: busybox:1.31.1
        command:
        - "/bin/sh"
        - "-c"
        args:
        - >
          chown 568:568 /config
        volumeMounts:
          - name: config
            mountPath: /config
    persistence:
      config:
        enabled: true
        skipuninstall: true
        existingClaim: ombi-config
```
It becomes this after the cluster pull:
```
---
kind: "HelmChart"
apiVersion: "helm.cattle.io/v1"
metadata:
  creationTimestamp: "2021-12-13T20:06:40Z"
  name: "ombi"
  namespace: "kube-system"
  resourceVersion: "15188801"
  uid: "0e4bf8b5-7169-4bb3-9cec-41c411773c6f"
spec:
  chart: "ombi"
  repo: "https://k8s-at-home.com/charts/"
  targetNamespace: "media"
  valuesContent: "image:\n  repository: ghcr.io/linuxserver/ombi\n  tag: version-v4.0.1430\n\
    env:\n  TZ: \"America/Chicago\"\n  PGID: 568\n  PUID: 568\ninitContainers:\n \
    \ chmod-config:      \n    name: chmod-config\n    image: busybox:1.31.1\n   \
    \ command:\n    - \"/bin/sh\"\n    - \"-c\"\n    args:\n    - >\n      chown 568:568\
    \ /config\n    volumeMounts:\n      - name: config\n        mountPath: /config\n\
    persistence:\n  config:\n    enabled: true\n    skipuninstall: true\n    existingClaim:\
    \ ombi-config"
```

**Comment by brunnels** [comment]
@adietish I don't know what your priorities are but for me a switch to disable/enable the cluster pull is very high.  I must keep the plugin disabled right now because the pull clobbers my local files.  If I forget to turn it off, I have to disable it and then VCS revert or use local history to undo the changes.

**Comment by brunnels** [comment]
@adietish I also noticed that it pulls from the server even if the namespace the file is in is not active.  I thought this might be a workaround to prevent the pull. Should I open another issue for this or is that intended behavior?

**Comment by adietish** [comment]
@brunnels awesome feedback even with example, thanks a lot! That's exactly what allows us to get as close as possible to what you need.  Removing the clutter is next in line and should be tackled very soon.

**Comment by adietish** [comment]
> @adietish I don't know what your priorities are but for me a switch to disable/enable the cluster pull is very high. I must keep the plugin disabled right now because the pull clobbers my local files. If I forget to turn it off, I have to disable it and then VCS revert or use local history to undo the changes.

@brunnels awesome feedback even with example, thanks a lot! That's exactly what allows us to get as close as possible to what you need.  Removing the clutter is next in line and should be tackled very soon so that you should be able to get off this very annoying workflow (sorry for that :)

**Comment by adietish** [comment]
> @adietish I also noticed that it pulls from the server even if the namespace the file is in is not active. I thought this might be a workaround to prevent the pull. Should I open another issue for this or is that intended behavior?

That's also a limitation that currently exists but is planned to be fixed: #283
The editor currently is fixed to the context (cluster, namespace, user) that was active when it was opened.

**Comment by adietish** [comment]
@brunnels I'm not sure if we can respect formatting though. So I it looks to me as if we - on top of removing the clutter -  should allow you to completely turn off the pulling as suggested with this issue 😄. Sounds about right?

**Comment by brunnels** [comment]
@adietish Yes please.  I would like to be able to turn off the auto pull.  Then if I want to pull I will use the buttons but most likely I would just use the compare feature when it's implemented to manually merge cluster and local if I need to.

**Comment by adietish** [comment]
@brunnels the change that you requested is coming these days. I can provide you with a binary that you can test a provide feedback if you want?

**Comment by adietish** [comment]
@jeffmaury:
> It looks completely broken to me. I tried on Red Hat Developer Sandbox and no projects are listed. 

Can you please provide steps so that I can reproduce this?

**Comment by jeffmaury** [comment]
1. Login to Sandbox
2. Copy the oc command line
3. Execute the oc command line on your desktop
4. Launch your PR
5. Expand the Project node
![image](https://user-images.githubusercontent.com/695993/152300900-c9a4af0f-9406-4151-ac5b-ddd6249de4fd.png)
6. Create a local pod.yml file
7. Insert the following content:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
```
![image](https://user-images.githubusercontent.com/695993/152301112-c2bfa9b5-0c51-4137-b359-c8df76a5d329.png)

**Comment by adietish** [comment]
@jeffmaury gotcha, could reproduce it. Filed it as #348
