### ISSUE TITLE
Push notification displayed on resource opening

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-kubernetes#324]
When i open a tekton task on cluster and this is opened in the editor, the push notification is shown. Nothing catastrophic but it is weird, i just opened a resource 8and there's no local change to it) there is no reason for me to push it.

It happens with all tekton resources but not with k8s native (e.g pods, daemonsets...)

![image](https://user-images.githubusercontent.com/49404737/146026610-6255223f-5639-47c7-96f4-b1acc04a1b52.png)

**Comment by adietish** [comment]
I can reproduce this. Investigating...

**Comment by adietish** [comment]
What I can see is that the local file and the resource I retrieve from the cluster differ in **metadata.generation**. I dont know why this is, currently.

**Comment by adietish** [comment]
Found the error. The "generation" property was deserialized as Int in earlier versions of the client. It is now correctly creating a Long.
