### ISSUE TITLE
As a user i would like to work with multiple resources in same editor tab

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-kubernetes#335]
The editor works fine with single resources but in many cases (tutorials, examples, export/import) users would have the necessity to write multiple resources in one single tab. It would be nice if the editor would be able to detect this and push all of the resources in that page together.

E.g by copy/paste the content of this example https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/conditional-pipelinerun.yaml and click on `push` i would expect to see all those resources deployed on my cluster.

The current outcome of copy/paste multiple resource in the same tab is 
![image](https://user-images.githubusercontent.com/49404737/147077168-fbebaf1c-d82f-469f-86a5-d109d9730b3a.png)

**Comment by adietish** [comment]
agree, noticed that too.

**Comment by adietish** [comment]
duplicate to #549. Closing.
