### ISSUE TITLE
Cannot push a knative broker - invalid yaml/json

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-kubernetes#403]
There are resources like brokers which doesn't have a spec body and the plugin considers them wrong erroneously.

Steps:
1) Have a broker resource
```
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
 name: default
```
2) open it in the editor
3) error is displayed

![image](https://user-images.githubusercontent.com/49404737/167562956-649ce291-efdc-4863-912c-3f35f8f5b80a.png)

**Comment by adietish** [comment]
Cannot reproduce it using latest `main` branch. Looks like this is fixed in latest source. @lstocchi told me that he was using the binary from marketplace. Can you reproduce it with latest source?

**Comment by lstocchi** [comment]
Tried with main branch and it works fine. Closing it. Thanks!!
