### ISSUE TITLE
Add links to the issue tracker and documentation in the IntelliJ marketplace and plugin description

### ISSUE THREAD

**Issue by themr0c** [redhat-developer/intellij-kubernetes#517]
As a user discovering the extension, I would like to see a link to the documentation and issue tracker in the IntelliJ marketplace web page, as well as in the plug-in description that appears in the IntelliJ plug-ins search (in Settings).

**Comment by jeffmaury** [comment]
![image](https://user-images.githubusercontent.com/695993/202414477-138fbecd-2373-498a-a09a-fe5a1220ee9e.png)

**Comment by adietish** [comment]
@themr0c thanks for reporting. Given that those are present on the plugin page, you want us to provide those in the plugin settings page, too? As far as I can see, no other plugin does this though.

**Comment by adietish** [comment]
@themr0c I'm closing this since we would not add those links to the plugin page in the IDEA preferences. Reopen this issue if you don't agree.
