### ISSUE TITLE
Should have sonar checks 

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#52]
We should have sonar checking the PRs and the whole codebase

CC: @sbouchet

**Comment by sbouchet** [comment]
I've experimented sonar checks locally using Gradle, and it should be straightforward.
It also exists a GitHub Action for Sonar but for now it does not support neither maven nor gradle base builds. 
 The only limit is to create/use secrets for being able to use the redhat sonar organization.

**Comment by adietish** [comment]
Added intellij-kubernetes to sonar and enabled PR checks:

![image](https://user-images.githubusercontent.com/25126/100891308-6c917c00-34b9-11eb-84d3-9deee9d09415.png)

**Comment by adietish** [comment]
Customizing rules sets is easily doable via the web frontend. Customizing rules is possible by hand-coding them. Examples are available at https://github.com/SonarSource/sonar-custom-rules-examples/tree/master/java-custom-rules/src/main/java/org/sonar/samples/java
I'd not go that far and code a custom rule for method naming that would allow the verbose method naming in tests. I wont disable that rule either since it makes a lot of sense in the context of normal code.

**Comment by sbouchet** [comment]
great! how did you manage to add intellij to sonar? thru the sonar web interface? i'd like to do same for intellij-openshift.

**Comment by adietish** [comment]
@sbouchet either via the IJ preferences or via https://plugins.jetbrains.com/plugin/7973-sonarlint where I hit the button "Install to IDE". Your local IJ would then start installing it. Neat!

But then, I only managed to get notifications in the IDE working. Analyzing code in the IDE doesn't work for me. It keeps complaining about an invalid project binding (weird enough if you consider that notifications work at the same time):
`2020-12-02 10:45:00,174 [1290675]  ERROR - SonarLintProjectAnalyzersPanel - Project is bound to a project that doesn't exist: redhat-developer_intellij-kubernetes`
Here are the matching settings as they're displayed in sonarcloud:
![image](https://user-images.githubusercontent.com/25126/100987131-6699aa80-354e-11eb-852e-1597565ba760.png)

And then, I currently also don't have test coverage reported correctly. Need to figure out what's wrong there.

**Comment by adietish** [comment]
filed lacking reporting of test coverage in #134
