### ISSUE TITLE
Editor: Adding a space after a value prompts me to push changes, should not

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#531]
**Steps:**
1. EXEC: edit existing resource
2. EXEC: add a " " after the value for kind
`kind: "Pod"` -> `kind: "Pod" `

**Result:**
Editor prompts me to push the change even though there is no real change to the editor.

**Expected result:**
Editor should not prompt me to push the changes since there are no real changes.

**Comment by olkornii** [comment]
@adietish 
Does not appear anymore. (v.0.7.1)

**Comment by adietish** [comment]
@olkornii thanks for confirming.
Closing.
