### ISSUE TITLE
 Recommend extension, based on installed operators

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#55]
depends on #208 

we should recommend to install ex. the tekton plugin if we detect that the cluster has tekton installed.
The very same was done in the openshift extension for vscode: https://github.com/redhat-developer/vscode-openshift-tools/pull/1587

**Comment by evidolob** [comment]
@adietish Please take an note, that in vscode we decide to base detection on CRD not an operator. See https://github.com/redhat-developer/vscode-openshift-tools/pull/1587#issuecomment-634761388

**Comment by adietish** [comment]
upon suggestion by @evidolob this was replaced by #225. Thanks for this hint!
