### ISSUE TITLE
provide "describe" like in vscode

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#553]
taken from https://github.com/redhat-developer/intellij-kubernetes/pull/548#issuecomment-1399406965
CC @cloorc

"Describe" is provided in the context menu of resource tree items in vscode. 
<img width="419" alt="image" src="https://user-images.githubusercontent.com/25126/214005270-c2cdc1b3-8ccd-4bdd-9dca-3c54b4e8d9e5.png">
It prints detailed informations about a k8s resources.
<img width="804" alt="image" src="https://user-images.githubusercontent.com/25126/214004723-3f55d1e8-2189-4d5a-b0a5-73143e7a15fb.png">

**Comment by adietish** [comment]
"Find" (Ctrl+F) is already helpful to pinpoint informations that one is looking for. Maybe a tree based display of the sections (Metadata, Containers, Conditions, Volumes, etc.) could help to get to the even more. A shortcut could be to print the informations as yaml since the yaml editor provides breadcrumb navigation and folding.

**Comment by cloorc** [comment]
> Yeah, that's what I mean. And I'm going to use kubectl command line tools from this pluggin to make it work.

**Comment by cloorc** [comment]
And further more, I will try to integrate helm command line ols too. That will enrich features as vscode plugin, which

**Comment by cloorc** [comment]
> And further more, I will try to integrate helm command line ols too. That will enrich features as vscode plugin, which has been added with at least 5 more features from the ms official one.

**Comment by cloorc** [comment]
> And further more, I will try to integrate helm command line ols too. That will enrich features as vscode plugin, which has been added with at least 5 more features from the ms official one.



> "Find" (Ctrl+F) is already helpful to pinpoint informations that one is looking for. Maybe a tree based display of the sections (Metadata, Containers, Conditions, Volumes, etc.) could help even more. A shortcut could be to print the informations as yaml since the yaml editor provides breadcrumb navigation and folding.
> 
> @cloorc: thoughts?

I'm gonna to try from shortcut to experience this feature thanks.

**Comment by adietish** [comment]
@cloorc we added basic HELM support in our [intellij-openshift-connector](https://plugins.jetbrains.com/plugin/12030-openshift-toolkit-by-red-hat) plugin: https://youtu.be/lvILs3fYJ2g

**Comment by cloorc** [comment]
Wonderful plugin, thanks for your excellent work. I'm going to try this.

**Comment by adietish** [comment]
jetbrains also allows to describe resources via the context menu:
<img width="1256" alt="image" src="https://github.com/redhat-developer/intellij-kubernetes/assets/25126/ba0e6810-d2b0-4fd0-9bff-6a8a601269d0">

The output is shown in an editor:
<img width="1501" alt="image" src="https://github.com/redhat-developer/intellij-kubernetes/assets/25126/efa7367f-e7a9-42d9-a007-9cc13b3add25">

**Comment by cloorc** [comment]
Sorry, I can't even build it from vscode online in codespace. It said `> /opt/java/11.0.14/Packages does not exist.`

**Comment by cloorc** [comment]
> Sorry, I can't even build it from vscode online in codespace. It said `> /opt/java/11.0.14/Packages does not exist.`

It seems like `Oracle JDK 11.0.23` can make it possible but not `OpenJDK 11.0.13`.

**Comment by adietish** [comment]
@cloorc that's odd, can't explain why this would happen. A question for the folks that develop the [java plugin for vscode](https://github.com/redhat-developer/vscode-java). On the other hand, this being an intellij-plugin, it's advisable to build and run in intellij even though it should be possible to build & run in vscode I guess (gradle managing all the requirements)

**Comment by cloorc** [comment]
> @cloorc that's odd, can't explain why this would happen. A question for the folks that develop the [java plugin for vscode](https://github.com/redhat-developer/vscode-java). On the other hand, this being an intellij-plugin, it's advisable to build and run in intellij even though it should be possible to build & run in vscode I guess (gradle managing all the requirements)

That's make sense.My network is poor and GitHub just provides a codespace that can be used to develop any project online. So I tried it and found this issue. I Guess there's something wrong with Gradle Intellij Plugin working with VSCode. It mostly not a issue related to this project.
