### ISSUE TITLE
add `helm releases` folder support

### ISSUE THREAD

**Issue by cloorc** [redhat-developer/intellij-kubernetes#556]
To provide `helm releases` features that are similar with `Helm Releases` in `Visual Studio Code` `Kubernetes Plugin` as folowing:

![image](https://user-images.githubusercontent.com/13597105/216592766-6bdb06a6-2866-4463-9351-03ebb964a293.png)

**Comment by adietish** [comment]
Releases are now listed in the intellij-openshift-connector, see https://github.com/redhat-developer/intellij-openshift-connector/issues/539.
There's currently no value in duplicating it for this plugin.
Closing.
