### ISSUE TITLE
"unable to find valid certification path to requested target" when trying to edit a resource

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#600]
This was reported in https://github.com/redhat-developer/intellij-kubernetes/issues/521#issuecomment-1549309067
**Steps:**
1. ASSERT: have an openshift cluster running on a private certificate
2. ASSERT: make sure it's the current context 
3. EXEC: in the plugin, open a resource (double click or "Edit.." in the ctx menu

**Result:**
Editor is opened but errors with the following details
```
PKIX path building failed: usn.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Adding the certificate under Settings -> Tools -> Server Certificates and also enabling "Accept non-trusted certificates automatically" doesn't help.

To reproduce this you can use our cluster bot:

**Steps:**
1. EXEC: using the clusterbot, launch a new instance (takes ~30min)
2. EXEC: log into the new cluster, copy the login command, paste it into bash/zsh and execute it
```
oc login --token=sha256~XXXXXXX --server=https://XXXXXXXX-east-1.amazonaws.com:6443
```
3. ASSERT: the command errors with the following that confirms that a private certificate is used:
```bash
error: tls: failed to verify certificate: x509: “kubernetes” certificate is not trusted
```
4. EXEC: add ` --insecure-skip-tls-verify=true` to the command
5. ASSERT: login is successful
6. EXEC: edit the entry for the new cluster in ~/.kube/config: remove ` insecure-skip-tls-verify: true`
7. EXEC: launch plugin (and maybe expand the `Projects` node)

**Result:**
The cluster is listed but not detected as OpenShift. Furthermore you cannot list any resources (expand nodes in the tree). They all error ("Error: Could not get ...")
In the IDEA log you discover the error:
```bash
Caused by: java.io.IOException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by adietish** [comment]
IDEA has settings for ssl certificates where the user can disable verification and add it's own certificates:
<img width="986" alt="image" src="https://github.com/redhat-developer/intellij-kubernetes/assets/25126/2775019b-cd07-4a58-91b6-ac031283ec4c">
The IDE would also ask the user for confirmation if certificates are not trusted.
In order to take advantage of these settings a plugin needs use the trust- and key-managers that the IDE offers. Our fabric8 kubernetes-client on the other hand, has its own key- and trust managers, that it creates and feeds to it's underlying http client. This means that the kubernetes plugin currently wont react to the settings that you set in the IDE preferences.

**Comment by adietish** [comment]
@tschut I have a first (quick and dirty) attempt to see if using the IDE certificate manager would help you:
You should get prompted with the IDEA certificate dialog if your certificate is untrusted. Once you accept it, it should show up in the list of trusted certificates in the IDEA settings. 
it's latest (revision 6) in my gist: https://gist.github.com/adietish/3aa8bec832cee37fd9abc3e6dfa6b684#file-kubernetes-by-red-hat-0-8-2-snapshot-zip

**Comment by adietish** [comment]
Hi @tschut
I told our client to accept all certificates and disable hostname verification. If this quick hack works for you then we know that certificates handling in the kubernetes-client is the cause of it. IN this cas we can then go ahead and find a way to plug the IDEA certificate handling into the client. Would be great if you could test it.
https://gist.github.com/adietish/3aa8bec832cee37fd9abc3e6dfa6b684#file-kubernetes-by-red-hat-0-8-2-snapshot-zip

**Comment by tschut** [comment]
Hi @adietish, didn't get around to testing it until now (was at springio 🥳)

It looks a lot better with this latest snapshot! I can login to the cluster, and when I open a resource.yaml in the editor I tested the "diff" and "pull" functions and both work correctly. 

What doesn't work yet is the browser in the OpenShift toolbox window. It shows the cluster, but the only item in the dropdown is "Unable to get namespaces: An error has occurred.", which is correct, because my account doesn't have the appropriate rights for `oc get namespaces`. It does for `oc get projects` though.

![image](https://github.com/redhat-developer/intellij-kubernetes/assets/1711214/f4030242-029b-4281-93dc-9626a31bc900)

**Comment by adietish** [comment]
for my own documentation purposes: 
I didnt succeed in having minikube run on a self-signed certificate. I managed it for CRC though:
**Steps:**
1. EXEC: create a self-signed certificate:
```
openssl genrsa -des3 -out domain.key 2048 // private key
openssl req -key domain.key -new -out domain.csr -subj "/CN=api.crc.testing" -addext "subjectAltName = DNS:api.crc.testing" // signing request
openssl x509 -signkey domain.key -in domain.csr -req -days 365 -out domain.crt // self-signed cert
openssl rsa -in domain.key -out domain.key.unencrypted -passin pass:<your password for domain.key> // private key without pw
```
2. EXEC: proceed as in https://docs.openshift.com/container-platform/4.13/security/certificates/api-server.html#api-server-certificates
```bash
crc start
oc login -u kubeadmin -p <password> https://api.crc.testing:6443
oc config view --flatten > kubeconfig-newapi
oc create secret tls selfsigned \
     --cert=domain.crt \
     --key=domain.key.unencrypted \
     -n openshift-config
oc patch apiserver cluster \
     --type=merge -p \
     '{"spec":{"servingCerts": {"namedCertificates":
     [{"names": ["api.crc.testing"], 
     "servingCertificate": {"name": "selfsigned"}}]}}}'
```

**Comment by adietish** [comment]
There's an easier way to reproduce this:
**Steps:**
1. EXEC: using the clusterbot, launch a new instance (takes ~30min)
2. EXEC: log into the new cluster, copy the login command, paste it into bash/zsh and execute it
3. ASSERT: the command errors with the following that confirms that a private certificate is used:
```
error: tls: failed to verify certificate: x509: “kubernetes” certificate is not trusted
```
4. EXEC: add ` --insecure-skip-tls-verify=true` to the command
5. ASSERT: login is successful
6. EXEC: edit the entry for the new cluster in ~/.kube/config: remove ` insecure-skip-tls-verify: true`
7. EXEC: launch plugin (and maybe expand the `Projects` node)
**Result:**
You are prompted to accept or reject the untrusted certificate for your cluster:
<img width="574" alt="image" src="https://github.com/redhat-developer/intellij-kubernetes/assets/25126/1072bbe3-ef3d-41ff-8151-cd37638199fd">
Once you accept it you can deal with your cluster in IDEA

**Comment by tschut** [comment]
> Hi @tschut, I now impl'd support for the IDEA certificate manager. You can now add your private certificate or blindly accept untrusted certificates in the IDEA settings. It would be beyond awesome if you could test this build? https://gist.github.com/adietish/3aa8bec832cee37fd9abc3e6dfa6b684#file-kubernetes-by-red-hat-0-8-2-snapshot-zip Would be greatly appreciated 😃

Nice work! I tried to validate the fix but since I already imported the certificates in my jdk I'd have to remove those first and I'm a bit busy atm :(

**Comment by adietish** [comment]
Hi @tschut, no problems, thanks for all the collab :) 
We'll release a 1.0.0 with this enhancement very soon. Feel free to report back if you face problems.
