### ISSUE TITLE
Use current Namespace/Project has a bug with minikube

### ISSUE THREAD

**Issue by olkornii** [redhat-developer/intellij-kubernetes#640]
Configurations:
  Kubernetes v1.26.2 on Docker 24.0.4
  openjdk 17.0.7 2023-04-18
  OS: Fedora 38
  Intellij 2023.1

Steps to reproduce:
1. Start minikube cluster
2. Expand Namespaces
3. Select namespace -> right click -> Use namespace -> tree refreshed (WRONG BEHAVIOR)
4. Repeat few times -> cluster name changes for short time (sometimes freezes)

On the video's 10 second is a bug.
[Screencast from 2023-07-24 12-22-10.webm](https://github.com/redhat-developer/intellij-kubernetes/assets/60704619/0c129321-6c3a-46a9-ae84-877bd7eec67d)

**Comment by adietish** [comment]
I cannot replicate this, I'm running MacOS though which may interfere.

**Comment by adietish** [comment]
#641 prevents minikube from being displayed as `<unknown context>`. It does not fix the collapsing of the context though. I thus keep this issue opened.

**Comment by adietish** [comment]
It looks as if the reason for the remaining bug is that the file watcher service in the jdk would send multiple (2+) events per file for a single modification. Several reports of this exist on stackoverflow:
* https://stackoverflow.com/questions/16777869/java-7-watchservice-ignoring-multiple-occurrences-of-the-same-event
* https://stackoverflow.com/questions/72953304/prevent-java-filewatcher-to-process-the-same-file-multiple-times
* https://stackoverflow.com/questions/39147735/watchservice-fires-entry-modify-sometimes-twice-and-sometimes-once

**Comment by adietish** [comment]
depends on https://github.com/redhat-developer/intellij-common/issues/190

**Comment by adietish** [comment]
Closing.
