### ISSUE TITLE
Current namespace is preserved when switching current context (only Linux, Windows?)

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#648]
I cannot replicate this on MacOS, this only happens to @olkornii using linux. He found it when testing #646

**Steps:**
1. ASSERT: have 2+ contexts in your kube config
2. EXEC: set a current namespace in the current context, that doesnt exist in the other context (ex. openshift-admin on an openshift cluster)
3. EXEC: switch to a different context (that doesn't have the namespace that exists in the prior context)
4. EXEC: verify the current namespace

**Result:**
The current namespace in the new context still is the namespace that was set in the previous context.

**Expected Result:**
The current namespace in the new context should be the first namespace that exists, not a namespace set in the previous context.

**Comment by adietish** [comment]
CC: @olkornii

**Comment by adietish** [comment]
I again tried to replicate this but couldn't. Can you @olkornii?

**Comment by olkornii** [comment]
Hi @adietish. I've tried again. Same as you, cannot reproduce anymore.
1. minikube v1.31.0, kubernetes v1.29.0
2. openshift 4.14.0 aws (Cluster Bot), oc 4.13.4-linux

**Comment by olkornii** [comment]
@adietish  I don't have openshift-admin namespace, but I've tried with openshift-apiserver and it works.

So my steps:
1. have 2 clusters (ex. openshift and minikube)
2. change namespace from defaut to openshift-apiserver
3. set minikube as current cluster
4. namespace is "default"
5. set openshift as current cluster
6. namespace is "openshift-apiserver"

**Comment by adietish** [comment]
Closing as we cannot reproduce it any more.
