### ISSUE TITLE
no release on Github for 1.1.0

### ISSUE THREAD

**Issue by sbouchet** [redhat-developer/intellij-kubernetes#656]
There is no release record/assets for 1.1.0 release on GH.

**Comment by adietish** [comment]
@sbouchet thanks for pointing out. Creating the issue.

**Comment by adietish** [comment]
I added Release [1.1.0](https://github.com/redhat-developer/intellij-kubernetes/releases/tag/1.1.0) and [1.0.1](https://github.com/redhat-developer/intellij-kubernetes/releases/tag/1.0.1)

**Comment by adietish** [comment]
Closing as RESOLVED.
