### ISSUE TITLE
Persistent Volume Claims (PVC) Not Shown

### ISSUE THREAD

**Issue by artntek** [redhat-developer/intellij-kubernetes#665]
### Steps to reproduce
* Ensure there are existing Persistent Volumes and Persistent Volume Claims in the Rancher Desktop cluster (see example below)
* Open IDEA and select Kubernetes tool pane
* Under "Rancher Desktop", expand "Storage", then expand "Persistent Volumes" and "Persistent Volume Claims"

### Expected
* "Persistent Volumes" should be populated with the PVs (total 9 in my case)
* "Persistent Volume Claims" should be populated with the PVCs (total 9 in my case)

### Actual
* The "Persistent Volumes" section correctly contains the 9 PVs
* The "Persistent Volume Claims" section is empty

#### Kubernetes tool pane
```
v rancher-desktop
  > Namespaces
  > Nodes
  > Workloads
  > Network

  v Storage
    v Persistent Volumes
      > pvc-53faee96-d22f-47af-97f5-9f59c8e8cdf8
      > pvc-3336af05-8f37-4d51-ad4b-ebfb0b818df2
      > pvc-37092798-69b0-4f81-b770-8be0f207de58
      > pvc-c360b4fd-7295-4167-ae6e-4447203a623e
      > pvc-21a895ae-6793-4075-95a7-7f192823a128
      > pvc-3ef02ca1-817f-4d2f-9289-d218198bb27b
      > pvc-f6ef3125-9d0e-4940-acc0-74ccea14a3fd
      > pvc-19dbfd8e-e191-4114-8dda-cc069184f97e
      > pvc-1102805e-d7e8-453c-bffc-8799b2537207

    v Persistent Volume Claims

    v Storage Classes
         local-path

  > Configuration
  > Custom Resources

```

##### PVs
```console
$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                              STORAGECLASS   REASON   AGE
pvc-53faee96-d22f-47af-97f5-9f59c8e8cdf8   1Gi        RWO            Delete           Bound    default/mc-volume-mc-metacat-0     local-path              18d
pvc-3336af05-8f37-4d51-ad4b-ebfb0b818df2   1Gi        RWO            Delete           Bound    default/data-mc-postgresql-0       local-path              18d
pvc-37092798-69b0-4f81-b770-8be0f207de58   8Gi        RWO            Delete           Bound    default/data-indexer-zookeeper-0   local-path              15h
pvc-c360b4fd-7295-4167-ae6e-4447203a623e   1Gi        RWO            Delete           Bound    default/data-indexer-solr-2        local-path              15h
pvc-21a895ae-6793-4075-95a7-7f192823a128   1Gi        RWO            Delete           Bound    default/data-indexer-solr-0        local-path              15h
pvc-3ef02ca1-817f-4d2f-9289-d218198bb27b   1Gi        RWO            Delete           Bound    default/data-indexer-solr-1        local-path              15h
pvc-f6ef3125-9d0e-4940-acc0-74ccea14a3fd   8Gi        RWO            Delete           Bound    default/data-indexer-zookeeper-2   local-path              15h
pvc-19dbfd8e-e191-4114-8dda-cc069184f97e   1Gi        RWO            Delete           Bound    default/data-indexer-rabbitmq-0    local-path              15h
pvc-1102805e-d7e8-453c-bffc-8799b2537207   8Gi        RWO            Delete           Bound    default/data-indexer-zookeeper-1   local-path              15h
```

##### PVCs
```console
$ kubectl get pvc
NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mc-volume-mc-metacat-0     Bound    pvc-53faee96-d22f-47af-97f5-9f59c8e8cdf8   1Gi        RWO            local-path     18d
data-mc-postgresql-0       Bound    pvc-3336af05-8f37-4d51-ad4b-ebfb0b818df2   1Gi        RWO            local-path     18d
data-indexer-zookeeper-0   Bound    pvc-37092798-69b0-4f81-b770-8be0f207de58   8Gi        RWO            local-path     15h
data-indexer-solr-2        Bound    pvc-c360b4fd-7295-4167-ae6e-4447203a623e   1Gi        RWO            local-path     15h
data-indexer-solr-0        Bound    pvc-21a895ae-6793-4075-95a7-7f192823a128   1Gi        RWO            local-path     15h
data-indexer-solr-1        Bound    pvc-3ef02ca1-817f-4d2f-9289-d218198bb27b   1Gi        RWO            local-path     15h
data-indexer-zookeeper-2   Bound    pvc-f6ef3125-9d0e-4940-acc0-74ccea14a3fd   8Gi        RWO            local-path     15h
data-indexer-rabbitmq-0    Bound    pvc-19dbfd8e-e191-4114-8dda-cc069184f97e   1Gi        RWO            local-path     15h
data-indexer-zookeeper-1   Bound    pvc-1102805e-d7e8-453c-bffc-8799b2537207   8Gi        RWO            local-path     15h
$
```

### Environment
* Kubernetes By RedHat plugin v. 1.2.0.271
* MacBook Pro 14" 2021 with Apple M1 Pro chip & 32GB RAM
* Mac OS Sonoma 14.0
* IntelliJ IDEA Community Edition - Build #IC-232.9921.47, built on September 12, 2023
* Rancher Desktop v. 1.10.0
* Kubernetes v. 1.27.5

**Comment by artntek** [comment]
Also happens in the same environment in RubyMine 2022.3.3 (Build #RM-223.8836.42, built on March 10, 2023)

**Comment by adietish** [comment]
Hi @artntek 
sorry for the late response, unfortunately missed your issue somehow.
Thanks for reporting it! I can replicate this. 
Will fix it and release a new version quickly :)

**Comment by adietish** [comment]
This error keeps me puzzled so far. 
I initially had no current namespace, had only PVs displayed (expected, PVCs are namespaced, none should come up. PVs are cluster scoped, so they should and are listed).
I then set the current namespace, still had no PVCs listed but once I had IDEA restarted, they got listed. 

@artntek I bet that you have a current namespace set, aren't you? Or are you experiencing it when switching the current namespace?

**Comment by artntek** [comment]
Ah! I had no namespace selected. When I select the `default` namespace (which is what I was using for my `kubectl` example commands above), the pvcs show up as expected.

So this is user error on my part; however, I'd expect the namespace to be automatically set to `default` if one is not set explicitly.

Thanks, and sorry for the false alarm.

**Comment by adietish** [comment]
@artntek Hi Matthew, lucky that this solved your issue. I agree that it's not properly brought to your attention that there's no  current namespace. 
I'd agree on listing the "default" namespace or the first of your namespaces given that `kubectl` does it too.
