### ISSUE TITLE
Cannot create or update resource with managed fields

### ISSUE THREAD

**Issue by olkornii** [redhat-developer/intellij-kubernetes#755]
Steps to reproduce:

1. start minikube cluster
2. find "minikube" in Nodes
3. Edit "minikube" node
4. change name to "anything"
5. see error notification

Expected: A new resource has been created
Actually: an error message:
```metadata.managedFields must be nil. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=metadata.managedFields must be nil, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).```

**Comment by adietish** [comment]
If you use "Remove Metadata clutter" in the editor toolbar you can successfully push the resource and it appears in the resource tree.

**Comment by adietish** [comment]
@olkornii: We are using a server-side patch operation to push the editor to the cluster and update it. The kubernetes docs specify that you cannot update the managed fields using a server-side patch operation which explains why we see this issue,
> It is however possible to change .metadata.managedFields through an update, or through a patch operation that does not use Server-Side Apply
One also seem not the able to create a resource with managed fields in this way. 
**Steps:**
1. EXEC: Create a file with the following content
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
  namespace: default
  labels:
    test-label: test
  managedFields:
    - manager: kubectl
      operation: Apply # note capitalization: "Apply" (or "Update")
      apiVersion: v1
      time: "2010-10-10T0:00:00Z"
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:test-label: {}
        f:data:
          f:key: {}
data:
  key: some value
```
2. EXEC: push the editor to the cluster.
**Result:** 
Error is displayed with the following details:
```
metadata.managedFields must be nil. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=metadata.managedFields must be nil, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
```

**Comment by adietish** [comment]
We cannot simply remove the fields before sending because the user may want to set those explicitly, we cannot assume that the're not worth sending. I need to see if there's a way for us to use a different saving mechanism like client-side apply that would succeed.
