### ISSUE TITLE
Option to disable PushNotification

### ISSUE THREAD

**Issue by JustinLex** [redhat-developer/intellij-kubernetes#763]
The PushNotification is not useful for GitOps workflows, and it is distracting to the user. There should be an option to disable the PushNotification. (i.e. the "Push to create Deployment 'foobar'?" notification)

**Comment by adietish** [comment]
Hi @JustinLex 

Am I right in thinking that you dont want any automatic sync with the cluster to happen? You only want to push & pull when you hit the toolbar buttons. Correct?

**Comment by adietish** [comment]
@JustinLex:
I now offer a setting where you can disable the editor trying to sync with the cluster:
<img width="981" alt="image" src="https://github.com/user-attachments/assets/31738b1b-e294-464d-a566-a62f199f7503">
If this is disabled you're not bothered to push your editor when it's modified (when compared to the cluster resource). Notifications of a deleted resource are not displayed either. You're still told of the result of pushing via the toolbar ("Resource was updated/created") and errors are notified, too, of course.
