### ISSUE TITLE
Release Plugin

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#88]
Now that we have a functional and useful plugin we should release the plugin.

**Comment by jeffmaury** [comment]
Required steps to complete before release:
- email should be developers@redhat.com
- vendor should Red-Hat to join JetBrains Red Hat organization

Optional step:
- change from namespace org.jboss.tools.intellij.kubernetes to com.redhat.devtools.intellij.kubernetes

**Comment by adietish** [comment]
Reopened bcs we still need several additional steps to publish the plugin.

**Comment by adietish** [comment]
Plugin has been published in the JetBrains Marketplace: https://plugins.jetbrains.com/plugin/15921-kubernetes-by-red-hat
